robot_name: 'franka'

eef_link: 'panda_grasptarget'

default_q: [
    0.0000, -0.7854,  0.0000, -2.4435,  0.0000,  1.6581,  0.75
]


joint_limit_buffers: [.01, .03, .01, .01, .01, .01, .01]

rmp_params:
    cspace_target_rmp:
        metric_scalar: 0.005
        position_gain: 100.
        damping_gain: 50.
        robust_position_term_thresh: .5
        inertia: 0.0001
    joint_limit_rmp:
        metric_scalar: 0.1
        metric_length_scale: .01
        metric_exploder_eps: .001
        metric_velocity_gate_length_scale: .01
        accel_damper_gain: 200.
        accel_potential_gain: 1.
        accel_potential_exploder_length_scale: .1
        accel_potential_exploder_eps: .01
    joint_velocity_cap_rmp:
        max_velocity: 1.7
        velocity_damping_region: 0.15
        damping_gain: 5.0
        metric_weight: 0.05
    target_rmp:
        accel_p_gain: 50.
        accel_d_gain: 70.
        accel_norm_eps: .075
        metric_alpha_length_scale: .05
        min_metric_alpha: .03
        max_metric_scalar: 1.0
        min_metric_scalar: 0.5
        proximity_metric_boost_scalar: 3.
        proximity_metric_boost_length_scale: .02
    collision_rmp:
        margin: 0.
        damping_gain: 50.
        damping_std_dev: .04
        damping_robustness_eps: .01
        damping_velocity_gate_length_scale: .01
        repulsion_gain: 800.
        repulsion_std_dev: .01
        metric_modulation_radius: .5
        metric_scalar: 1.
        metric_exploder_std_dev: .02
        metric_exploder_eps: .001
    damping_rmp:
        accel_d_gain: 30.
        metric_scalar: 0.005
        inertia: 0.3

body_obstacles: []

arm_collision_controllers:
    - segment: [panda_link1, panda_link3]
      interpolation_pts: 10
      radius: .1
    - segment: [panda_forearm_end_pt, panda_forearm_mid_pt]
      interpolation_pts: 5
      radius: .1
    - segment: [panda_forearm_mid_pt_shifted, panda_forearm_distal]
      interpolation_pts: 5
      radius: .075
    - segment: [panda_wrist_end_pt, panda_link8]
      interpolation_pts: 8
      radius: .05
    - segment: [panda_face_back_left, panda_face_back_right]
      interpolation_pts: 5
      radius: .03
      suppression_name: right_gripper
    - segment: [panda_face_left, panda_face_right]
      interpolation_pts: 5
      radius: .02
      suppression_name: right_gripper
    - segment: [panda_hand, panda_leftfingertip]
      interpolation_pts: 5
      radius: .01
      suppression_name: right_gripper
    - segment: [panda_hand, panda_rightfingertip]
      interpolation_pts: 5
      radius: .01
      suppression_name: right_gripper
